database:
  user: "meuse"
  password: "meuse"
  host: "127.0.0.1"
  port: 5432
  name: "meuse"
http:
  address: 127.0.0.1
  port: 8855
logging:
  level: debug
  console: true
  overrides:
    org.apache.http: error
    io.netty.buffer.PoolThreadCache: error
metadata:
  path: "/home/mathieu/prog/rust/testregistry"
  target: "origin/master"
  url: "https://github.com/mcorbin/testregistry"
crate:
  path: "/home/mathieu/prog/rust/crates"
