database:
  user: "meuse"
  password: "meuse"
  subname: "//127.0.0.1:5432/meuse"
http:
  address: 127.0.0.1
  port: 8855
logging:
  level: debug
  console: true
  overrides:
    com.mchange.v2.c3p0: error
metadata:
  path: "/home/mathieu/prog/rust/testregistry"
  target: "origin/master"
  url: "https://github.com/mcorbin/testregistry"
crate:
  path: "/home/mathieu/prog/rust/crates"
