database:
  user: "meuse"
  password: "meuse"
  subname: "//127.0.0.1:5432/meuse"
http:
  address: 127.0.0.1
  port: 8855
logging:
  level: info
  console: true
metadata:
  path: "/home/mathieu/prog/rust/testregistry"
  target: "origin/master"
crate:
  path: "/home/mathieu/prog/rust/crates"
